version: '3'

services:
  php:
    build: ./docker/php
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    ports:
      - "8080:8080"
    volumes:
      - ./server:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    links:
      - db

  db:
    image: oracle/database:19.3.0-ee
    container_name: oracle
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./docker/db/data:/opt/oracle/oradata
    environment:
      - ORACLE_PWD=Oracle19
      - ORACLE_PDB=oracle

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - php
    links:
      - php
